### ISSUE TITLE
BUG: VISR missing text file? 

### ISSUE THREAD

**Issue by jlmaurer** [kmaterna/Strain_2D#11]
## Description
-When running VISR method, get an error message saying missing text file, but the file exists in the current directory.

**Comment by kmaterna** [comment]
@jlmaurer interesting, that doesn't happen to me, but I think I've seen it before.  A few thoughts: 
The Python wrapper for visr creates these files in the working directory (where driver or config.txt lives):
``` 
strain_config_file = 'visr_strain.drv';
strain_data_file = 'strain_input.txt';  # can only be 20 characters long bc fortran!
strain_output_file = 'strain_output.txt';  # can only be 20 characters long bc fortran!
```
And then it automatically moves them into the visr output directory when it's done.  When I run it, I can see them written in the same directory as the config and then I watch them get moved.   Which directory do you find them in?  Perhaps it's writing them in the wrong place or automatically moving them too early?

**Comment by jlmaurer** [comment]
Hey @kmaterna yes I think the files were left in the main execute directory for me instead of getting moved. Not sure why yet, I'll investigate and update this issue.

**Comment by kmaterna** [comment]
@jlmaurer when you say that, I immediately suspect differences in the behavior of subprocess.call(shell=False) or subprocess.call(shell=True) on your system vs mine.  shell=False is more secure so I try to use it whenever possible, but a small subset of commands don't work unless shell=True.  This is a rabbit hole I haven't wanted to enter.  I'd start there with your investigation.
