### ISSUE TITLE
Geostats strain values with possible units problem

### ISSUE THREAD

**Issue by kmaterna** [kmaterna/Strain_2D#15]
@jlmaurer I got geostats working!   But even with several sets of parameter choices, I suspect a units problem (off by 1000) in the strain or velocity output grids.  Top: comparative max_shear, regular for the first 4, but I multiply geostats' max_shear by 1000.  Bottom:  standard Strain_2D plots of dilatation and 2nd invariant from my geostats run.  The 2nd invariant plot is clearer about the 1000x thing.  
<img width="1498" alt="Screen Shot 2021-09-29 at 6 36 51 PM" src="https://user-images.githubusercontent.com/12519252/135371477-fcdd59ff-34bd-46ba-a802-0c6f13685869.png">

By the way, I couldn't help myself and made a few cosmetic changes (no change in function) to the geostats file, based on IDE stuff.  I hopefully didn't do anything too overbearing or controversial; it helps me see any real problems through a pared-down set of IDE warnings.

**Comment by jlmaurer** [comment]
Not a problem!

Interesting, but I think if I remember correctly there was an off-by-1000
issue elsewhere we fixed a while back. Probably I had written geostats to
be consistent with he older version, and now it's different. That's what I
would guess, can check into it or you can as well!

Jeremy

**Comment by kmaterna** [comment]
@jlmaurer I put in a fix to do 1000x.  Seems to be working so far.  We will talk results next time. 

I also built this .md when I didn't feel like doing other things: https://github.com/kmaterna/Strain_2D/blob/master/param_definitions.md
