### ISSUE TITLE
Bug in max shear strain rate calculation

### ISSUE THREAD

**Issue by jlmaurer** [kmaterna/Strain_2D#16]
Hey @kmaterna I introduced a bug in the max shear strain rate code by propagating a bug from my last code. The current syntax is 

(1) tau_{max} = sqrt((e_{11}-e_{22})^2 + e_{12}^2)

but after some extensive work with Kaj Johnson we figured out that the formula should actually be 

(2) tau_{max} = sqrt((e_{11}-e_{22})^2 + **4*e_{12}**^2).

The factor of 4 is missing from the current formulation. It can make a difference of a factor of 1-2 depending on the tensor. 

The way we worked this out was to analytically calculate the principal strains and take the difference. Max shear strain rate is just the difference between e1 and e2. Solving for the eigenvalues of the strain rate tensor and taking the difference results in Eq. 2 above. 

See [here](https://github.com/kmaterna/Strain_2D/blob/6415562672901131e0139b3c407dd7be204722b0/Strain_Tools/strain/strain_tensor_toolbox.py#L68) for line in question.

**Comment by kmaterna** [comment]
@jlmaurer awesome.  This fix is supported by Savage and Simpson 1997 Equation 2.   They have tau_max exactly as you and Kaj suggested.
