### ISSUE TITLE
Don't plot strain rate tensors in water

### ISSUE THREAD

**Issue by jlmaurer** [kmaterna/Strain_2D#19]
Not sure how easy this is in GMT/PyGMT but I'm thinking it will be best to mask out strain rate tensors over water, even though in some cases it might be interesting to see them. I'm finding in areas with a large amount of water (i.e. Hispaniola) we're getting unrealistic strain tensors well offshore. Maybe we can figure out a way to only plot them within a buffer distance of shore or something.

**Comment by kmaterna** [comment]
Good idea.  I'll look into "gmt grdlandmask" options.  It's easy in gmt; never tried it in pygmt.

**Comment by kmaterna** [comment]
Fixed in commit [785fbea](https://github.com/kmaterna/Strain_2D/commit/785fbea91eb9d4e8cccf38a979f51c24c51def40).  FYI I needed to upgrade PYGMT on the conda environment to get grdlandmask function; probably a good idea every once in a while. 
'conda install pygmt --update-all'
