### ISSUE TITLE
Max/Min or principal strain rates

### ISSUE THREAD

**Issue by 2295360453CNU** [kmaterna/Strain_2D#21]
Hello, I noticed that in the output .nc file, there is no Max/min or principal strain rates and "azimuth angle", but in your program output diagram there is principal strain rates, just like the cross line in other diagrams, so how should I calculate the principal strain rate if I want to use my own plot script;
In addition, when input the config.txt, how should I input the parameter of "inc"? I find that the calculated results (the value range) vary greatly depending on the input value. Do you have any suggestions?

**Comment by kmaterna** [comment]
Hi, thanks for using the code!  you can calculate any derived strain quantity you need to from the 3 layers ```exx```, ```exy```, and ```eyy``` in the output netcdf.   For principal strain rates at a given point, we use the eigenvector function on the three components of the strain tensor.  You can write one into your plotting script or use the same one we use as a starting point ([found here](https://github.com/kmaterna/Strain_2D/blob/e0750077c4e862cb88c0490d99185e32b3a04f42/Strain_Tools/strain/strain_tensor_toolbox.py#L90) )

The "inc" parameter is meant to be the grid spacing of the desired grid in the x and y directions, in degrees, separated by a slash.  I usually use ```inc = 0.02/0.02``` for my applications.  The size of the output grids will obviously decrease if you make the grid spacing larger for the same geographic domain.  Make sure that there's a space around the equals sign, same as for all parameters.  Does that help?
