### ISSUE TITLE
Strain Comparison- Output Directory Not Found

### ISSUE THREAD

**Issue by kashyap-t** [kmaterna/Strain_2D#25]
The strain comparison program does not read the pathway in which the Output is stored.

**Comment by kmaterna** [comment]
Hi, thanks for using our code. Could you provide a bit more detail, like the error message?  I'm suspecting something is pointing to the wrong place.  The ```input_dirs``` parameter for ```strain_rate_comparison.py``` from the config file is just a list of paths for reading the computations you've already done.  You might need to change the folders being named, if you called them something different when you computed them.  The general ```output_dir``` and the paths in ```input_dirs``` need to match.  

```
[general]
output_dir = output

[strain-comparison]
output_dir = output/_strain_comparison
input_dirs = output/gpsgridder:output/visr:output/loc_avg_grad:output/wavelets:output/geostats
```
