### ISSUE TITLE
Issue running Strain_2D on Windows

### ISSUE THREAD

**Issue by Ampanas** [kmaterna/Strain_2D#30]
Hi, 

I am trying to run Strain_2D on Windows 11 (Python3.11, numpy, scipy, matplotlib and pygmt all latest versions installed). I have installed setup.py and want to recreate the image in the example but I run into the following error: 

![image](https://github.com/kmaterna/Strain_2D/assets/144361899/a1176dde-8c5f-4570-b993-c00dc83fd5b9)

Any help from anyone who has successfully run the program on Windows (11) would be appreciated.

Thanks in advance.

Ampanas

**Comment by kmaterna** [comment]
Hello, 
Thank you for using the library and reporting this bug.  It seems like you're really close, but subprocess has trouble starting processes on Windows.  I just submitted a small change to replace the subprocess usages with native Python libraries os and shutil.  There's still one usage of subprocess left in Strain_2D, but it's a GMT call way down at the end, hopefully it won't break, and I we'll cross that bridge when we get to it.  
Can you try the sequence again with a fresh clone/pull the repo and setup.py install?  If it doesn't work right away, I'll take a closer look later with a real Windows system to test.   Thanks!

**Comment by Ampanas** [comment]
> Hello, Thank you for using the library and reporting this bug. It seems like you're really close, but subprocess has trouble starting processes on Windows. I just submitted a small change to replace the subprocess usages with native Python libraries os and shutil. There's still one usage of subprocess left in Strain_2D, but it's a GMT call way down at the end, hopefully it won't break, and I we'll cross that bridge when we get to it. Can you try the sequence again with a fresh clone/pull the repo and setup.py install? If it doesn't work right away, I'll take a closer look later with a real Windows system to test. Thanks!

Hello, 
Thanks for your reply. The changes you submitted worked! I am now able to run Strain_2D on Windows 11. See below the results for the delaunay approach.
 
![Strain_2D - Delaunay](https://github.com/kmaterna/Strain_2D/assets/144361899/bd2f6caf-069d-428b-8561-095d1090bbf6)

Thanks again!

Ampanas
