### ISSUE TITLE
How to edit scale on colorbar

### ISSUE THREAD

**Issue by st4rh0pe** [kmaterna/Strain_2D#31]
As explained in the title, how do i edit max and minimum value of my colorbar so that the contrast would be more visible? i've tried to edited it but nothing change

**Comment by kmaterna** [comment]
Hello!  Oh you’re right, it looks like all the min/max values in the plots
(pygmt_plots.py) are hard-coded.   If you change those values in the code,
you have to re-run ```python setup.py install``` every time (in the right
conda environment).  Did you try that?

In the longer term we could make them user parameters, but for now just try
the install route.  Let’s come back to that if it doesn’t work.
