### ISSUE TITLE
Add a Python-based VISR implementation

### ISSUE THREAD

**Issue by tobiscode** [kmaterna/Strain_2D#40]
Just a meta issue tracking my fork and then subsequent PR to merge a Python-based, simple VISR method to Strain_2D.

**Comment by tobiscode** [comment]
@kmaterna I had a quick question about coordinate systems while porting my code. Do I understand correctly that the Delaunay and other Python-based method assume that lon/lat is a cartesian grid? Because in my implementation I convert everything to the closest UTM representation and then do the calculations. Since `pyproj` isn't a requirement (or a similar package), I wouldn't be able to do that.

Also feel free to assign me to this issue.

**Comment by jlmaurer** [comment]
@tobiscode we implement a regular grid in lat/lon space, which is a distorted grid in cartesian space. To calculate grid cell area we use a cosine correction (see e.g. [ here](https://github.com/kmaterna/Strain_2D/blob/1c95fab0669717f55d212e205be63cff72d96e9a/Strain_Tools/strain/models/strain_geostats.py#L171)).

**Comment by tobiscode** [comment]
Hi,
after looking again at the code and the downgrades I'd have to make to use the cosine-correction grid approximation, I was hoping I'd just be able to add `pyproj` as a dependency. It's a pretty standard and well-maintained package that's already required by every other mapping package (e.g., `basemap`, `cartopy` and `pygmt`), and using it would reduce the error sources and make the coding for me much easier. Is that okay?
Thanks!

**Comment by kmaterna** [comment]
@tobiscode I did have to ```conda install pyproj``` when I checked out your branch (not really sure why since pygmt is a requirement, but whatever).  I'm happy to add that to the requirements.yml after we merge your PR.

**Comment by tobiscode** [comment]
Ahh I see what's happening, I just tried to do a fresh environment installation. I think `pygmt` only needs the underlying`proj` library, but not the Python wrapper `pyproj` since I'm assuming GMT calls PROJ directly. If you could add `pyproj` directly as a requirement, that would be fantastic, thanks.

Cheers
